### ISSUE TITLE
Linode Label not always String

### ISSUE THREAD

**Issue by theckman** [taoh/linodego#1]
Unfortunately, when Linode serializes JSON it can change types depending on the key's value. For example, a Linode's label isn't always a string. If you were to rename your Linode to `12345` and tried to use this package it looks like it won't work properly.

This is, unfortunately, due to a limitation of the programming language used by Linode for their API. The issue can't be fixed on their end and needs to be mitigated in the client.

A Linode's label isn't the only key that can be impacted by this.

**Comment by theckman** [comment]
@taoh I noticed you checked in an API key as part of the fix. Is this a valid key? Is this intentional?

**Comment by taoh** [comment]
Thanks @theckman! The key was used for testing and has been invalidated.
